isPublic: true
name: 'Public Schema'
scope:
  - 'sections.be3e72bb-38ca-4f58-bd17-f2275ed86445:read' # Homepage
  - 'entrytypes.ea6cc2b9-0fba-4314-ac10-4f4b7e537ac6:read' # Homepage
  - 'sections.921a50dd-e864-421e-9040-abeab5f11e28:read' # Projects
  - 'entrytypes.06dd5d56-4715-4a58-bbe3-e14e9f0a872d:read' # Projects
