columnSuffix: null
contentColumnType: string
fieldGroup: c1760756-8587-4691-84da-ff9231459601 # Components
handle: project
instructions: ''
name: Project
searchable: false
settings:
  contentTable: '{{%matrixcontent_project}}'
  maxBlocks: '1'
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
