defaultPlacement: end
enableVersioning: true
handle: homepage
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  211de2ac-e52f-46dd-91e3-14a166b4addb: # Just Dev It Backend
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
